# APIキーの設定
consumer_key:        'x3ll9JoNoBa8vXqZfpZmD55R6'
consumer_key_secret: 'NzNQnJdArUJ0qwLaBG1iI7Xeg2DWEjeVygViAilccXxCibIcmk'
access_token:        '2924262206-DNCkzZASA2NykUJe4MvqbGAfESsqlNxgkPUUMJ2'
access_token_secret: 'dUZvVTBn3x3BDt1NiFKJKOhlzD4hozOt4MG9p3pREicts'

# botのデータ保存先
savefile: 'bot.dat'

# 本文末尾につける文字列
footer: ''

# テストモード（0：本番1：投稿処理をパス）
testmode: 0
